### ISSUE TITLE
Получение более 100 последних постов

### ISSUE THREAD

**Issue by Gzblizz** [qwertyadrian/TG_AutoPoster#11]
Приветствую а есть возможность обойти ограничения в 100 последних постов из группы?
Если нужно достать все посты за пару лет последних, может каким то циклом пробегаться или api вк не даст?

**Comment by qwertyadrian** [comment]
Максимальное число постов, которое можно получить с помощью метода [wall.get](https://vk.com/dev/wall.get) за один вызов, равняется 100. Можно получить большее число постов, используя смещение, необходимое для выборки определенного подмножества. Но использование этого смещения не было мной предусмотрено.
В общем реализовать это возможно, нужно будет над этим подумать.

**Comment by Gzblizz** [comment]
А вот еще такой мини вопрос, реально ли как то получить "источник" из поста вк?
В самом Api вк есть когда отправляешь поста источника а вот обратно не нашел такого, источник ссылка на твитер и всякое такое

**Comment by qwertyadrian** [comment]
> получить "источник" из поста вк

Да, конечно. Нужно только добавить эту в возможность в бота.

**Comment by qwertyadrian** [comment]
Было реализовано в [TG_AutoPoster 3.1](https://github.com/qwertyadrian/TG_AutoPoster/releases/tag/3.1)
