### ISSUE TITLE
socket.send() raised exception.

### ISSUE THREAD

**Issue by NoAdO** [qwertyadrian/TG_AutoPoster#12]
**Опишите ошибку**
В какой-то момент бот перестает репостить новые сообщения. В логах повторяется "socket.send() raised exception." без подробностей, ресарт контейнера решает проблему.

**Как получить ошибку**
Шаги для воспроизведения ошибки: неизвестно

**Ваш ПК (пожалуйста, укажите следующую информацию):**
 - OS: Docker Image, latest
 - Источник установки Docker Hub
 - Приложите файл конфигурации бота
 - ID группы (пользователя) и ID проблемного поста: https://vk.com/wall-154341181_7686 но пост каждый раз разный. В предыдущий раз это был https://vk.com/wall-154341181_7623 и общего у них только то что они в одной группе.

**Дополнительная информация**
[config без токенов.yaml.txt](https://github.com/qwertyadrian/TG_AutoPoster/files/9034501/config.yaml.txt)

stop.ini
`#storm08travel`

Может как-нибудь заставить контейнер писать в папку с конфигом подробный лог? хоть будет понятно в какой момент случился затык, последний строчки все одинаковые.

**Comment by qwertyadrian** [comment]
Это ошибка, появляющаяся в используемом мной фреймворке Pyrogram и исправить её у меня нет возможности. Бот и его зависимости были обновлены, это должно помочь.

> Может как-нибудь заставить контейнер писать в папку с конфигом подробный лог? хоть будет понятно в какой момент случился затык, последний строчки все одинаковые.

Для этого есть параметр командной строки `--debug` (`-d`).

**Comment by NoAdO** [comment]
Вчерашнюю запись (вчера в 18:33) опубликовало сейчас, в 16:30. В логах тишина. Перезапустил контейнер с опцией --debug, вижу её работу в логах. Буду наблюдать дальше.

**Comment by qwertyadrian** [comment]
Я столкнулся с той же ошибкой, но после обновления уже третий день бот работает без перебоев.

**Comment by NoAdO** [comment]
Поправлю себя: пост был опубликован вовремя И спустя сутки. Почему так - не знаю. Пока других проблем не вижу.

**Comment by NoAdO** [comment]
Ошибок больше не было
