### ISSUE TITLE
Несколько замечаний 

### ISSUE THREAD

**Issue by Gzblizz** [qwertyadrian/TG_AutoPoster#14]
А есть ли возможность доставать из постов не ссылки на видео VK а на оригинал с ютуба?
А еще в parse_photo нету проверки на ошибку, бывало такое что пять картинок скачалось а шестая не грузится битая и бот падал в ошибку, по правил ручками обвернув в try.
Ну и очень очень редкое, но если в посте VK больше чем 1 gif загружена то бот тоже падает в ошибку, так как с вк он скачивает все gif а вот в телеграмм не может их отправить

**Comment by qwertyadrian** [comment]
Ссылки на оригинал видео, думаю, можно достать. Нужно будет изучить этот вопрос.
Проверка на ошибки при скачивании фото будет добавлена.
Ошибка с отправкой GIF анимаций была исправлена в последнем релизе (подробнее: #13).
