### ISSUE TITLE
Скрипт

### ISSUE THREAD

**Issue by Freenstaip** [qwertyadrian/TG_AutoPoster#15]
Добрый день, подскажите пожалуйста, никак не могу со скриптом разобраться, вроде все данные заполнил, но при запуске в логах появляется такая ошибка, как можно исправить?
![12](https://user-images.githubusercontent.com/111694697/185798138-3cfbd71b-a52a-4130-bf11-4b8ab8828f11.jpg)

**Comment by qwertyadrian** [comment]
Здравствуйте. Предоставьте, пожалуйста, полный лог файл, а не его часть. А также предоставьте файл конфигурации. В будущем используйте [эту форму](https://github.com/qwertyadrian/TG_AutoPoster/issues/new?assignees=qwertyadrian&labels=bug&template=---------------.md&title=) для создания отчетов об ошибке.

**Comment by Freenstaip** [comment]
[bot_log_2022-08-21_15-36-47_592776.log.txt](https://github.com/qwertyadrian/TG_AutoPoster/files/9389454/bot_log_2022-08-21_15-36-47_592776.log.txt)
[config.txt](https://github.com/qwertyadrian/TG_AutoPoster/files/9389459/config.txt)

**Comment by qwertyadrian** [comment]
По неизвестной мне причине бот не успел полностью загрузиться до отправки сообщения. Какую версию бота вы используете, откуда он установлен? И какой командой запускается бот? 

В любом случае исправление этой ошибки будет в ближайшем релизе, но если вы используете последнюю версию бота из GitHub (ветка `master`), то исправление будет доступно в ближайшие часы.

**Comment by Freenstaip** [comment]
Версия [3.3.0b2]
Запуск по python3 -m TG_AutoPoster
Хорошо, тогда буду ждать, спасибо)

**Comment by Freenstaip** [comment]
Бот заработал, спасибо. Ещё вопрос, когда новые посты в Вк публикуют бот их игнорирует, изначально запостил старые посты и всё, подскажите, можно ли сделать, чтоб бот публиковал и новые записи?

**Comment by qwertyadrian** [comment]
По умолчанию бот проверяет последние 11 постов группы каждый час.

**Comment by Freenstaip** [comment]
Благодарю, спасибо)
