### ISSUE TITLE
Добавить настройку стоп слов / слов для удаления прямо в ТГ

### ISSUE THREAD

**Issue by FunnHik** [qwertyadrian/TG_AutoPoster#18]
Хотелось бы делать данные настройки прямо в телеграмме.

**Comment by Gzblizz** [comment]
А еще бы отключение логирования или это не возможно так легко?
Чаще всего эти логированные файла просто так записываются и лежат

**Comment by qwertyadrian** [comment]
> А еще бы отключение логирования или это не возможно так легко?

Возможно. Я подумаю над этим.

**Comment by qwertyadrian** [comment]
Реализовано в TG_AutoPoster 3.5.0.
