### ISSUE TITLE
PytzUsageWarning

### ISSUE THREAD

**Issue by vladios13** [qwertyadrian/TG_AutoPoster#20]
**Опишите ошибку**
При запуске скрипта: python3 -m TG_AutoPoster получаю: 

```
/usr/local/lib/python3.7/dist-packages/apscheduler/util.py:94: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
/usr/local/lib/python3.7/dist-packages/apscheduler/util.py:165: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tz.localize(datetime_, is_dst=None)
/usr/local/lib/python3.7/dist-packages/apscheduler/triggers/interval.py:66: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(next_fire_time)
```
**Лог-файл**
[bot_log_2022-09-20_14-18-29_028792_DEBUG.log](https://github.com/qwertyadrian/TG_AutoPoster/files/9606945/bot_log_2022-09-20_14-18-29_028792_DEBUG.log)

**Ваш ПК (пожалуйста, укажите следующую информацию):**
 - OS: Debian 10
 - Python Version: 3.7.3
 - Версия бота 3.4
 - Источник установки: GitHub.

**Comment by qwertyadrian** [comment]
Это не ошибки, а предупреждения в библиотеке [apscheduler](https://github.com/agronholm/apscheduler/discussions/570), которые не должны влиять на работу бота. По словам автора библиотеки эти предупреждения будут убраны в будущем релизе.

Единственное, что я могу - заглушить эти предупреждения.

**Comment by qwertyadrian** [comment]
Реализовано в TG_AutoPoster 3.5.0.
