### ISSUE TITLE
Вместо GIF сделать mp4

### ISSUE THREAD

**Issue by LexsaTV** [qwertyadrian/TG_AutoPoster#21]
Здравствуйте а возможно скачивать с вк не gif?
Так как через браузер можно сохранить как видео, так как если в одном посту есть много текста плюс картинки плюс 1-2 gif то получается это все не 1 сообщением в TG а в 4
Первое сообщения это большой текст (но тут я понимаю ограничения телеграма и возможно с покупкой премиум это решиться)
Второе сообщения это картинки (так как если пост больше сколько то символов вместе с вложениями просит купить премиум)
Третий пост это GIF ну и 4 пост вторая GIF
Но вот если это видео то можно сразу загружать в один пост вместе с картинками.
Как по это лучший вариант

**Comment by qwertyadrian** [comment]
> Здравствуйте а возможно скачивать с вк не gif?

Да, ВК API позволяет скачать GIF как видео. Будет сделано в ближайших релизах.

> ограничения телеграма и возможно с покупкой премиум это решиться

Это так, но на данный момент боты не могут использовать возможности премиум. Но это можно обойти если использовать аккаунт пользователя с премиумом вместо бота.

**Comment by LexsaTV** [comment]
Но что бы использовать вместо бота, аккаунт пользователя это нужно как я понимаю дописывать еще функции?
Было бы удобно возможно в будущем иметь вариант.
Странно что ботам не дают премиум, если у создателя этих ботов он куплен.
Спасибо за уточнения про премиум

**Comment by LexsaTV** [comment]
А обновление будет из беты?

**Comment by qwertyadrian** [comment]
Обновление будет, но точных сроков я назвать пока не могу.

**Comment by qwertyadrian** [comment]
> Да, ВК API позволяет скачать GIF как видео. Будет сделано в ближайших релизах.

К сожалению, мною было обнаружено, что из-за ограничений Telegram все видео без звука считает GIF анимацией поэтому их нельзя отправить вместе с обычными видео (со звуком) и/или картинками одним сообщением. Соответственно этот функционал не будет реализован.

**Comment by LexsaTV** [comment]
Сделаю уточнение, все можно
Если отправить просто mp4 без звука будет GIF
Но если отправить mp4 (все так же без звука) плюс картинку то будет видео, я только что это сделал 
Порядок не важен сначала картинка потом видео или видео потом картинка, телеграм все делает из него обычное видео

**Comment by qwertyadrian** [comment]
Но в [биспользуемой мной библиотеке](https://github.com/pyrogram/pyrogram/issues/729) так не работает. Хотя это происходит при отправке видео, а отправку картинки и видео без звука одним сообщением я не пробовал.

Я попробую что-нибудь придумать, но не могу дать никаких гарантий.

**Comment by vladios13** [comment]
> Я попробую что-нибудь придумать, но не могу дать никаких гарантий.

Как один из простых вариантов, на mp4 контейнер без звуковой дорожки, накинуть пустую дорожку силами ffmpeg.

Пример:
`ffmpeg -i 1.mp4 -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -c:v copy -shortest output.mp4`

Происходит на лету, в итоге в Telegram будет отображаться как видео, потому что такой mp4 контейнер имеет пустой звук на все длине видео.

**Comment by LexsaTV** [comment]
Как я понял это добавлять не будешь?

**Comment by qwertyadrian** [comment]
Пока не могу сказать, так как на разработку бота сейчас совсем нет свободного времени.

**Comment by LexsaTV** [comment]
Вернешься к этой функции? Раз снова обновляешь бота

**Comment by qwertyadrian** [comment]
> Вернешься к этой функции? Раз снова обновляешь бота

Да, сделаю в одном из будущих релизов.

> Как один из простых вариантов, на mp4 контейнер без звуковой дорожки, накинуть пустую дорожку силами ffmpeg.

Идея хорошая, правда хотелось бы это сделать без помощи ffmpeg.
