### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Freenstaip** [qwertyadrian/TG_AutoPoster#23]
**Опишите ошибку**
После обновления, при отправке постов тг канал, начала появляться ошибка ApiError

**Как получить ошибку**
Шаги для воспроизведения ошибки:
1. Go to 'Запуск скрипта'
2. Click on 'Ожидание отправки постов'
3. Scroll down to 'Ошибка'

**Ожидаемое поведение**
Отправка постов ТГ канал

**Лог-файл**
Загрузите лог-файл бота, запущенного в режиме отладки (параметр `--debug`).

**Ваш ПК (пожалуйста, укажите следующую информацию):**
 - OS: [Windows]
 - Python Version: [3.8]
 - Версия бота [e.g. 3.3.1]
 - Источник установки (GitHub)
 - Приложите файл конфигурации бота
 - Ссылка на проблемный пост

**Дополнительная информация**
[bot_log_2022-11-04_06-36-44_434137.log](https://github.com/qwertyadrian/TG_AutoPoster/files/9935703/bot_log_2022-11-04_06-36-44_434137.log)

**Comment by qwertyadrian** [comment]
В файле конфигурации значение `<https://vk.com/kinogive>` не должно иметь угловых скобок.
