### ISSUE TITLE
Альбомы

### ISSUE THREAD

**Issue by LexsaTV** [qwertyadrian/TG_AutoPoster#24]
Если на стене группы находится просто альбом в котором условно 20-50 фото то бот постит в тг лишь ссылку на него, было бы не плохо что бы он и это умел парсить в несколько постов подрят

**Comment by qwertyadrian** [comment]
В начале разработки бота хотел так сделать, но позже отказался от этого, так как если в альбоме слишком много фото, то они все отправляются из-за чего чат или канал «засоряются».
