### ISSUE TITLE
Путь для конфиг файла config.yaml

### ISSUE THREAD

**Issue by YoshiKill** [qwertyadrian/TG_AutoPoster#35]
Приветсвую, задам нубский вопрос. Так и не смог понять где именно нужно создавать файл конфигурации из инструкции config.yaml
Подскажите путь.

**Comment by qwertyadrian** [comment]
Файл конфигурации должен быть расположен в директории, из которой бот будет запущен. Или же можно указать полный путь к файлу конфигурации, запустив бота с параметром `--config путь_к_файлу_конфигурации`
