### ISSUE TITLE
Все в одном посте

### ISSUE THREAD

**Issue by vladios13** [qwertyadrian/TG_AutoPoster#4]
**Текущая реализация**
Если пост, имеет текст и альбом (несколько изображений), то вывод текста идет отдельным сообщениям от медиа. 
![пример](https://i.13.yt/2019/10/17/1571299219-4993.png?raw=true "Пример такого поста")

**Идея улучшения**
Если пост, имеет текст и альбом (несколько изображений), то вывод текста **прикреплять** к первому изображению.

**Comment by qwertyadrian** [comment]
В принципе я реализовал это, но к таким постам по техническим причинам нельзя добавить кнопки с ссылками на автора поста и оригинал поста. Разве что в таком случае отправлять эти кнопки вместе с дополнительным сообщением.

**Comment by qwertyadrian** [comment]
Теперь текст приклепляется к первому изображению. Исправлено в последнем коммите.
