### ISSUE TITLE
режим loop для Docker

### ISSUE THREAD

**Issue by NoAdO** [qwertyadrian/TG_AutoPoster#8]
**Идея улучшения***
Сейчас скрипт может работать "по кругу" благодаря аргументам -l и -s . Просьба заключается в возможности добавить этот режим для докер-контейнера через переключалку в ENV или что-то подобное.

**Comment by qwertyadrian** [comment]
В последнем обновлении была добавлена поддержка переменных окружения.

**Comment by NoAdO** [comment]
Большое спасибо
