### ISSUE TITLE
Не работают репосты

### ISSUE THREAD

**Issue by smotim** [qwertyadrian/TG_AutoPoster#9]
**Когда группа делает репост, Autoposter не видит его**

**Как получить ошибку**
1. Делаем репост в группе
2. Пишем в конфиге id поста за несколько постов до целевого
3. Запускаем 
4. Приходят все посты, кроме последнего (с репостом). В конфиге как id_last запишется id последнего поста без репостов

**ПК**
 - Zorin OS 16 (основан на Ubuntu)
 - Python 3.8.10
- Ссылка на группу, в которой пытался https://vk.com/project__it. 
- Последний раз пробовал на посте 639

**Comment by smotim** [comment]
я логинюсь через токен, тк на аккаунте двухфакторка. Вдруг это влияет

**Comment by qwertyadrian** [comment]
Проверил работоспособность отправки репостов с использованием сервисного ключа доступа. Да, баг и правда есть, правда немного не в том виде как вы его описали. Он уже исправлен в одном из последних коммитов.

**Comment by smotim** [comment]
> Проверил работоспособность отправки репостов с использованием сервисного ключа доступа. Да, баг и правда есть, правда немного не в том виде как вы его описали. Он уже исправлен в одном из последних коммитов.

Спасибо! Наверное скоро проверю. С постами без медиафайлов видел, что тоже исправлено теперь. А можно сделать какую-нибудь проверку обновлений бота при запуске?

**Comment by qwertyadrian** [comment]
> А можно сделать какую-нибудь проверку обновлений бота при запуске?
Я подумаю что с этим можно сделать.
